apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.resourceName" (dict "ctx" . "component" "querier") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "querier") | nindent 4 }}
  {{- with .Values.querier.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    {{- range $key, $value := .Values.ports.querier }}
    {{- if $value.servicePort }}
    - name: {{ $key }}
      port: {{ $value.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ $value.protocol }}
      {{- if and (hasPrefix $key "grpc") ($.Values.querier.appProtocol.grpc) }}
      appProtocol: {{ $.Values.querier.appProtocol.grpc }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "tempo.selectorLabels" (dict "ctx" . "component" "querier" "memberlist" true) | nindent 4 }}
