apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.resourceName" (dict "ctx" . "component" "compactor") }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "compactor") | nindent 4 }}
  {{- with .Values.compactor.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    {{- range $key, $value := .Values.ports.compactor }}
    {{- if $value.servicePort }}
    - name: {{ $key }}
      port: {{ $value.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ $value.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "tempo.selectorLabels" (dict "ctx" . "component" "compactor") | nindent 4 }}
