{{- if .Values.enterprise.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "admin-api") }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "admin-api" "memberlist" true) | nindent 4 }}
    {{- with .Values.adminApi.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.adminApi.service.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    {{- range $key, $value := .Values.ports.adminApi }}
    {{- if $value.servicePort }}
    - name: {{ $key }}
      port: {{ $value.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ $value.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "tempo.selectorLabels" (dict "ctx" . "component" "admin-api" "memberlist" true) | nindent 4 }}
{{- end -}}
