{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "gateway") }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "gateway") | nindent 4 }}
    {{- with .Values.gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  {{- with .Values.gateway.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if and (eq "LoadBalancer" .Values.gateway.service.type) .Values.gateway.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- range $key, $value := .Values.ports.gateway }}
    {{- if $value.servicePort }}
    - name: {{ $key }}
      port: {{ $value.servicePort }}
      targetPort: {{  $key }}
      protocol: {{ $value.protocol }}
      {{- if $value.nodePort }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "tempo.selectorLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
{{- end }}
