apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "query-frontend") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
  {{- with .Values.queryFrontend.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.queryFrontend.service.type }}
  ports:
    {{- range $key, $value := .Values.ports.queryFrontend }}
    {{- if $value.servicePort }}
    - name: {{ $key }}
      port: {{ $value.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ .protocol }}
      {{- if and (hasPrefix $key "grpc") ($.Values.queryFrontend.appProtocol.grpc) }}
      appProtocol: {{ $.Values.queryFrontend.appProtocol.grpc }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.queryFrontend.query.enabled }}
    {{- range $key, $value := .Values.ports.tempoQuery }}
    {{- if $value.servicePort }}
    - name: {{ $key }}
      port: {{ $value.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ .protocol }}
      {{- if and (hasPrefix $key "grpc") ($.Values.queryFrontend.appProtocol.grpc) }}
      appProtocol: {{ $.Values.queryFrontend.appProtocol.grpc }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- if .Values.queryFrontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.queryFrontend.service.loadBalancerIP  }}
  {{- end }}
  {{- with .Values.queryFrontend.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "tempo.selectorLabels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
