apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "query-frontend-discovery") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
  {{- with .Values.queryFrontend.serviceDiscovery.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range .Values.ports.queryFrontend }}
    {{- if .serviceDiscoverPort }}
    - name: {{ .name }}
      port: {{ .serviceDiscoverPort }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- else }}
      targetPort: {{ .name }}
      {{- end }}
      protocol: {{ .protocol }}
      {{- if and (hasPrefix .name "grpc") ($.Values.queryFrontend.appProtocol.grpc) }}
      appProtocol: {{ $.Values.queryFrontend.appProtocol.grpc }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.queryFrontend.query.enabled }}
    {{- range .Values.ports.tempoQuery }}
    {{- if .servicePort }}
    - name: {{ .name }}
      port: {{ .servicePort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      {{- if and (hasPrefix .name "grpc") ($.Values.queryFrontend.appProtocol.grpc) }}
      appProtocol: {{ $.Values.queryFrontend.appProtocol.grpc }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "tempo.selectorLabels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
