{{- $dict := dict "ctx" . "component" "ingester" true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
  {{- with .Values.ingester.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    {{- range $key, $value := .Values.ports.ingester }}
    {{- if $value.servicePort }}
    - name: {{ $key }}
      port: {{ $value.servicePort }}
      targetPort: {{ $key }}
      protocol: {{ $value.protocol }}
      {{- if and (hasPrefix $key "grpc") ($.Values.ingester.appProtocol.grpc) }}
      appProtocol: {{ $.Values.ingester.appProtocol.grpc }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "tempo.selectorLabels" $dict | nindent 4 }}
